#pragma once

enum AppState {
    STATE_TITLE,
    STATE_GETSTARTED,
    STATE_CREATE_ACCOUNT,
    STATE_LOGIN,
    STATE_FORGOT_PASSWORD,
    STATE_EMAIL_PASSWORD,
    STATE_USERNAME,
    STATE_CONFIRMATION,
    STATE_MAIN_MENU,
    STATE_HOME,
    STATE_STATISTICS,
    STATE_LEADERBOARD,
    STATE_GAME_BOARD,
    STATE_RESTART_CONFIRM,
    STATE_SAVE_CONFIRM
};
